#!/usr/bin/env bash
# This bash script configures Nginx to running and listening on port 80 in an Ubuntu container.
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
