#!/usr/bin/env bash
# Displaying a list of currently running processes.
# Showing all processes, for all users, including those
# that might not have a TTY
# Displaying in a user-oriented format
# And showing process hierarchy

ps -auxf
