#!/usr/bin/env bash
# Displaying To infinity and beyond indefinitely
# With a sleep 2 in between each iteration
# You are invincible!!! when receiving a SIGTERM signal

while true
do 
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
